### ISSUE TITLE
CFG Lock

### ISSUE THREAD

**Issue by ildoddo** [barijaona/OpenCore_GA-Z170X-Gaming5#2]
Hello,
perhaps there's a typo on guide for CFG Lock.
You have write to type the command setup_var 0x4FE 0x00, but this return an error.
In fact I calculate the right offset with the help of OpenCore guide and the right command is:
setup_var 0x4EF 0x00
The VerifyMsr2 tool, confirm CFG unlocked after this.
I have F20 bios version.
Thanks for the guide.

**Comment by barijaona** [comment]
You're right ! Thanks for the feedback
