### ISSUE TITLE
can not see install macOS

### ISSUE THREAD

**Issue by loveuqian** [barijaona/OpenCore_GA-Z170X-Gaming5#4]
can you tell me the probelm is ?

![图片](https://user-images.githubusercontent.com/9745332/111069889-2d3be800-850a-11eb-80b5-45e6d583fa26.png)

![图片](https://user-images.githubusercontent.com/9745332/111069895-33ca5f80-850a-11eb-9a21-0700d1fd8ef3.png)

**Comment by barijaona** [comment]
For an initial install, you will need to use a large enough USB key with macOS installer prepared through Apple's createinstallmedia :

https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by barijaona** [comment]
As pointed out in issue #5 , setting ScanPolicy to 0 may help.

**Comment by loveuqian** [comment]
thanks for the replay
