### ISSUE TITLE
USB drives not found by open core

### ISSUE THREAD

**Issue by sh-rp** [barijaona/OpenCore_GA-Z170X-Gaming5#5]
Hey @barijaona, I'm already really grateful for your open core build which works great for my very similar setup, so consider some beers owed :). I do have one question though. When booting from your open core build, the open core boot selection screen does not seem to be able to find any of my usb drives. I tried with a Catalina and a Big Sur drive which both get found, and can be started, by a clover EFI I still had. Can you reproduce this problem or do you know anything about it? I worked around it by starting by using clover on the usb drive to start the install and then I could use open core as the main boot loader on the hdd where I have installed Catalina, but of course it would be nice to go fully open core.

**Comment by sh-rp** [comment]
Ok, so for anyone reading here, setting the ScanPolicy to 0 in the config.plist shows all available drives. Somehow the OpenCore manuals are not well indexed by google it seems, otherwise I would've found this solution quite fast I think.

**Comment by barijaona** [comment]
You're right, I found the ScanPolicy I use in OpenCore's Sample.plist
Might be good to change this to be more flexible, but it may impact security.
